### ISSUE TITLE
Better differentiate EEVP vs. precincts reporting

### ISSUE THREAD

**Issue by audreycarlsen** [nprapps/elections20-interactive#138]
As per Sean, can we make this more clear in tooltips and tables?

**Comment by alykat** [comment]
I wasn't able to articulate this clearly when we all talked about it, but I feel like what we're showing as "% in" is the best measurement we have of how many votes have been tabulated in a given race/geography. Where the best measure is EEVP, we use that; otherwise, precincts reporting. I still feel like footnoting when/where we use each is sufficient.

**Comment by audreycarlsen** [comment]
Agreed!
